package com.bank.lms.service;

import com.bank.lms.dto.CustomerEnquiryDto;
import com.bank.lms.entity.Customer;
import com.bank.lms.repository.CustomerRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import com.bank.lms.dto.CustomerResponseDto;

@Service
@RequiredArgsConstructor
public class CustomerService {

    private final CustomerRepository customerRepository;

    public String registerCustomer(CustomerEnquiryDto dto) {
        // 1. Business Validation: Check if PAN already exists
        if (customerRepository.existsByPanNo(dto.getPanNo())) {
            throw new RuntimeException("A customer with this PAN number is already registered.");
        }

        // 2. Map DTO to Entity
        Customer customer = new Customer();
        customer.setPanNo(dto.getPanNo());
        customer.setFullName(dto.getFullName());
        customer.setPhoneNo(dto.getPhoneNo());
        customer.setEmail(dto.getEmail());
        customer.setDob(dto.getDob());

        customer.setBranchCode(dto.getBranchCode());
        // Note: cifNo is auto-generated by the database
        // 2. Generate a unique 12-digit account number automatically
        // Using current time in milliseconds is a quick way to ensure uniqueness for your project
        String generatedAccString = "3040" + System.currentTimeMillis();
        Long finalAccountNumber = Long.valueOf(generatedAccString.substring(0, 12));

        customer.setAccountNumber(finalAccountNumber);
        // 3. Save to Database
        customerRepository.save(customer);

        return "Customer successfully registered with PAN: " + customer.getPanNo();
    }
    public CustomerResponseDto getCustomerByAccount(Long accountNumber) {
        // 1. Fetch the entity from the database
        Customer customer = customerRepository.findByAccountNumber(accountNumber)
                .orElseThrow(() -> new RuntimeException("Customer not found with account number: " + accountNumber));

        // 2. Map the entity data to the safe DTO
        CustomerResponseDto responseDto = new CustomerResponseDto();
        responseDto.setFullName(customer.getFullName());
        responseDto.setAccountNumber(customer.getAccountNumber());
        responseDto.setEmail(customer.getEmail());
        responseDto.setPhoneNo(customer.getPhoneNo());
        responseDto.setBranchCode(customer.getBranchCode());

        return responseDto;
    }
}